#!/bin/sh

file=$1
dir=$(dirname $file)

echo "<nav>"

for item in $(ls ${dir}/*.md); do
	item=$(basename $item .md)
	echo "\t<a href=\"${item}.html\">${item}</a>"
done

for item in $(find $dir -maxdepth 1 -type d); do
	if [ "$item" = "$dir" ]; then continue; fi
	item=$(basename $item)
	echo "\t<a href=\"${item}\">${item}</a>"
done

echo "</nav>"
